{% set name = "clize" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 047f5a4473602718ab1b85672a7e15303387178d5a81c275dc429dfac1ecb510

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - attrs >=19.1.0,<20
    - docutils
    - od
    - python >=2.7
    - sigtools >=2.0
    - six

test:
  imports:
    - clize
    - clize.tests

about:
  home: https://clize.readthedocs.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Turn functions into command-line interfaces
  dev_url: https://github.com/epsy/clize
  doc_url: https://clize.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - proinsias
