travis:
  secure:
    BINSTAR_TOKEN: J++PefJCvLc1JC9K2w9DKq9FXfny5+VN+/yN9cYMsUkcB9WCzyeJy8v9odjPfSGSOqs+MoPxfYgq9WBsaBIWZwpp9YxskRttuz4LOXBNLI6Tmn8oPmAYlTjVS7oU5kkN3KeVyv+TvikCxIs84Zvc/Nibk0Teem6qsl1ElAeL2SRW7XC/XIMHU9THisOGSXU5er/H9JeU7CUYnggS8gfz6bbq7Pum1stL90dajzDv7rGe5/X5JAFLrrrA0f2H2BJdRm0flyy2a/oIQBB96bxV9+tJM9954Nuk5O66hhchmW3BQb+t6XoVZ6BcJ1Mvk9BWIhtKkxtYLdz1yCVqU78YjC9U8rnz2MdXIhIizOorEtiQWDB8lya6MloP6p8lHzppXiO7+Tfs1Kk1Yym5PS2wJ9S4Zipzm5v1f9Ic+Y9s3wSn2OYAtAUEfx4b9EsHncoVRTP1wZiyx3gzMp+Q5tnrpjtQl/khsEQjAQ2EsRk1d9uIM8yC2XTB8CqCbkbLZL5PusQITp/gHxVyEUz/VXE65JZVC6mpt6Mvd45l6+BuH3uO1Kx/x7HYM764ucDT2ZOwx4GQKh7bWiXT/enTFgZ1sQ6/mRhEGqFAgEkAX8k0HMegI/QGRSgPmk4WTlosI5PKTVruuNWu6+dEpvNsc/GPoR6Ym0FQQw4Gw+BrIJX7wic=
conda_forge_output_validation: true
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
